apiVersion: datamesh.org/v1alpha1
kind: DataProduct
metadata:
  name: dpo01
  domain: nhic-dpo01
  description: "Data product demo 01"
  version: 0.1.0
  tags:
    - tag1
    - tag2
spec:
  owner:
    team: platformteam
    email: omakala@sandtech.com
  inputs:
    - name: input-source-name
      source: source-domain/source-dataset
      description: "Description of input data"
      schema: "https://schema-registry/schemas/input-schema"
  outputs:
    - name: output-name
      description: "Description of output data"
      schema: "https://schema-registry/schemas/output-schema"
      endpoint: "/api/nhic/dpo01"
      format: "json"
  sla:
    freshness: 24h  # How often the data is updated
    availability: 99.9%  # SLA target
  documentation:
    usage: "https://docs.example.com/data-products/nhic/dpo01"
    codeRepository: "https://github.com/oscarmakala/nhic-dpo01"
  lineage:
    upstream:
      - source-domain/source-dataset
    downstream: []