        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: dp01
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: dp01
          template:
            metadata:
              labels:
                app: dp01
              annotations:
                prometheus.io/scrape: "true"
                prometheus.io/path: "/metrics"
                prometheus.io/port: "8000"
            spec:
              containers:
              - name: dp01
                image: ghcr.io/oscarmakala/nhic-dpo01/dpo01:a80a3cf860071a30e70efe4c4600e2499f85a373
                ports:
                - containerPort: 8000
                resources:
                  requests:
                    memory: "256Mi"
                    cpu: "100m"
                  limits:
                    memory: "512Mi"
                    cpu: "200m"
                readinessProbe:
                  httpGet:
                    path: /health
                    port: 8000
                  initialDelaySeconds: 5
                  periodSeconds: 10
                livenessProbe:
                  httpGet:
                    path: /health
                    port: 8000
                  initialDelaySeconds: 15
                  periodSeconds: 20
                env:
                - name: PORT
                  value: "8000"
        ---
        apiVersion: v1
        kind: Service
        metadata:
          name: dp01
        spec:
          selector:
            app: dp01
          ports:
          - port: 80
            targetPort: 8000
          type: ClusterIP