name: Data Product CI/CD

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Extract metadata
        id: metadata
        run: |
          echo "domain=$(grep -m 1 'domain:' metadata.yaml | cut -d ':' -f 2 | xargs)" >> $GITHUB_OUTPUT
          echo "name=$(grep -m 1 'name:' metadata.yaml | cut -d ':' -f 2 | xargs)" >> $GITHUB_OUTPUT
          
      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/oscarmakala/${{ steps.metadata.outputs.domain }}/${{ steps.metadata.outputs.name }}:latest

#      - name: Update Kubernetes manifests
#        run: |
#          sed -i "s|image:.*|image: ${{ secrets.REGISTRY_URL }}/${{ steps.metadata.outputs.domain }}/${{ steps.metadata.outputs.name }}:${{ github.sha }}|g" k8s/deployment.yaml
#
#      - name: Commit and push updated manifests
#        uses: stefanzweifel/git-auto-commit-action@v4
#        with:
#          commit_message: "Update image to ${{ github.sha }}"
#          file_pattern: k8s/deployment.yaml